---
name: "Docker"

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: amd64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm

    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Extract branch or tag name
        run: |
          if [[ -n "${GITHUB_HEAD_REF}" ]]; then
            # This is a PR, use the source branch name
            echo "REF_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          else
            # This is a push, use the branch or tag name from GITHUB_REF
            echo "REF_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Set TAG
        run: |
          if [[ "${{ env.REF_NAME }}" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=${{ env.REF_NAME }}" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v6
        with:
          file: console/Dockerfile
          tags: |
            ghcr.io/${{github.repository}}:${{matrix.arch}}-console-latest
          push: true
      - uses: docker/build-push-action@v6
        with:
          file: automation/Dockerfile
          tags: |
            ghcr.io/${{github.repository}}:${{matrix.arch}}-automation-latest
          push: true
